HISTFILESIZE=5000

# useful aliases
alias vim="nvim"
alias vi="nvim"

alias ll="ls -lh"
alias la="ls -alh"

alias sublime="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"

# solarized colors
export PS1="\[\e[00;35m\]\u\[\e[0m\]@\[\e[00;36m\]\h\[\e[0m\]:\[\e[00;33m\]\w \[\e[0m\]$ "
export CLICOLOR=1

# grep colors
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='1;31;1'
